# marine-term-translations/setup-harvest-action/action.yml
name: 'Harvest NERC Vocabulary'
description: 'Harvests a NERC collection and updates translations.db'

inputs:
  collection-url:
    description: 'URL of the NERC collection to harvest (e.g. P02, L05, etc.)'
    required: true
    default: 'http://vocab.nerc.ac.uk/collection/P02/current/'
  github-token:
    description: 'Token to push back to repo'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - run: pip install SPARQLWrapper==2.0.0 rdflib==7.4.0
    - run: python ${{ github.action_path }}/harvest.py "${{ inputs.collection-url }}"
      shell: bash
    - run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add translations.db
        git diff --staged --quiet || (git commit -m "chore: update translations.db (${{ inputs.collection-url }})" && git push)