name: 'Harvest NERC Vocab Collection'
description: 'Query a NERC vocab collection from SPARQL endpoint and save to SQLite database'
author: 'marine-term-translations'

inputs:
  collection-uri:
    description: 'URI of the collection to query'
    required: true

outputs:
  database-path:
    description: 'Path to the generated SQLite database (always translations.db in repo root)'
    value: 'translations.db'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.collection-uri }}

branding:
  icon: 'database'
  color: 'blue'
