# marine-term-translations/setup-harvest-action/action.yml
name: 'Harvest NERC Vocabulary'
description: 'Harvests a NERC collection and commits updated translations.db'

inputs:
  collection-url:
    description: 'NERC collection URL'
    required: true
    default: 'http://vocab.nerc.ac.uk/collection/P02/current/'
  token:
    description: 'PAT with repo write permission'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.token }}

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install --no-cache-dir SPARQLWrapper==2.0.0 rdflib==7.4.0
      shell: bash

    - name: Harvest collection
      run: python ${{ github.action_path }}/harvest.py "${{ inputs.collection-url }}"
      shell: bash

    - name: Commit & push if changed
      run: |
        git config user.name "gitea-actions[bot]"
        git config user.email "actions@noreply.users.gitea"
        git add translations.db

        if git diff --staged --quiet; then
          echo "No changes in translations.db"
          exit 0
        fi

        git commit -m "chore: update translations.db – ${{ inputs.collection-url }} [skip ci]"
        git push
      shell: bash