name: "Harvest NERC Vocabulary"
description: "Harvests a NERC collection and auto-commits translations.db back to the calling repo"
inputs:
  collection-uri:
    required: true
    description: "e.g. http://vocab.nerc.ac.uk/collection/P02/current/"
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install SPARQLWrapper
      run: pip install SPARQLWrapper
      shell: bash

    - name: Run harvest script (with auto-commit+push)
      run: python ${{ github.action_path }}/harvest.py "${{ inputs.collection-uri }}"
      env:
        # These env vars are injected automatically by Gitea/GitHub
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # Gitea uses the same name!
        GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}     # fallback
      shell: bash